fail_fast: false
files:  |
      (?x)^(
          ./main.cxx|
          ./foo.cxx
      )$
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: 336fdd7c3cab698ead0b1c95157b9e74d3906b62
    hooks:
      - id: clang-format
      - id: clang-tidy
        args: [--enable-module-headers-parsing, --extra-arg=-std=c++26, --extra-arg=-stdlib=libc++, -p=build/debug]
      # - id: oclint
      # - id: uncrustify
      - id: cppcheck
      # - id: cpplint
      # - id: include-what-you-use
