fail_fast: false
files: ^main.cpp
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: 336fdd7c3cab698ead0b1c95157b9e74d3906b62
    hooks:
      - id: clang-format
        args: [--version=18]
      - id: clang-tidy
        args: [--version=18, --extra-arg=-std=c++2b, --extra-arg=-stdlib=libc++]
      # - id: oclint
      # - id: uncrustify
      - id: cppcheck
      # - id: cpplint
      # - id: include-what-you-use