name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
    # paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc']
env:
  DAY_OF_WEEK: Monday

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cppcheck
      run: sudo apt install cppcheck
    - name: Install llvm
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    - name: Install standard library headers for clang and clang tools
      run: sudo apt install clang-tidy-18 clang-format-18
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
    - name: Configure
      run: pip install pre-commit cpplint && pre-commit install && pre-commit autoupdate --bleeding-edge
    - name: Build project
      run: ./scripts/make_debug.sh
    - name: Run pre-commit on changed files
      run: pre-commit run
    - name: Save value of pre-commit in Github output variable
      run:  echo "pre-commit-result=$?" && echo "pre-commit-result=$?" >>  $GITHUB_OUTPUT  
      id: run_pre_commit
    - name: Pre-commit check
      if: steps.run_pre_commit.outputs.pre-commit-result > 0
      run: exit 1
