name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cppcheck
        run: sudo app install cppcheck
    - name: Install include-what-you-use
        run: sudo app install include-what-you-use
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1